name: TicketManager
version: '${project.version}'
main: net.ticketmanager.TicketManagerPlugin
author: Amps
description: Coming Soon
api-version: '1.21'
commands:
  ticket:
    description: Main command for ticket management.
    usage: /ticket <create|list|assign|close|reload|prune>
    aliases: [tickets]
    permission: ticketmanager.use
    permission-message: "&cYou do not have permission to use this command."
  ticketgui:
    description: Opens the ticket management GUI.
    permission: ticketmanager.gui
    permission-message: "&cYou do not have permission to use this command."
permissions:
  ticketmanager.use:
    description: Allows the player to use the /ticket command.
    default: true
  ticketmanager.create:
    description: Allows the player to create a ticket.
    default: true
  ticketmanager.list:
    description: Allows the player to list tickets.
    default: op
  ticketmanager.assign:
    description: Allows the player to assign tickets.
    default: op
  ticketmanager.close:
    description: Allows the player to close tickets.
    default: op
  ticketmanager.reload:
    description: Allows the player to reload the TicketManager configuration.
    default: op
  ticketmanager.notify:
    description: Notifies the player of new tickets and unresolved tickets on join.
    default: op
  ticketmanager.gui:
    description: Allows the player to use the /ticket gui command.
    default: op
  ticketmanager.prune:
    description: Allows the player to prune old tickets.
    default: op